#Github
safe:	      true
lsi:          false
pygments:     true
source:       .

# Dependencies
markdown:     rdiscount

# Permalinks
#permalink:    pretty

# Server
baseurl:      /freehep-vectorgraphics
destination:  ./_site
exclude:      []
keep_files:   ['.git', '.svn']

port:         9001
url:          http://localhost:9001
