# Dependencies
markdown:     rdiscount
#pygments:     true

# Permalinks
#permalink:    pretty

# Server
baseurl:      /freehep-vectorgraphics
source:       .
destination:  ./_site
exclude:      []
keep_files:   ['.git', '.svn']

port:         9001
url:          http://localhost:9001
